name: Forgotten Server 1.4 Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python for Google Drive Download
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install gdown for Google Drive Download
      run: pip install gdown
    
    - name: Download Server.zip from Google Drive
      run: |
        gdown 1mbP66SZCS0jK7DKeQKb3PcvdgtmDdDNq
    
    - name: Extract Server.zip
      run: |
        Expand-Archive -Path Server.zip -DestinationPath ./server
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Setup vcpkg
      uses: friendlyanon/setup-vcpkg@v1
      with:
        vcpkg-triplet: x64-windows
        vcpkg-cache-key: '${{ runner.os }}-vcpkg'
    
    - name: Install Dependencies via vcpkg
      run: |
        vcpkg install boost:x64-windows
        vcpkg install openssl:x64-windows
        vcpkg install mysql-connector-cpp:x64-windows
        vcpkg install asio:x64-windows
        vcpkg integrate install
    
    - name: Configure CMake
      run: |
        cd server
        cmake -B build -DCMAKE_TOOLCHAIN_FILE=${{ env.VCPKG_ROOT }}/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows
    
    - name: Build Project
      run: |
        cd server
        cmake --build build --config Release
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: tfs-windows-build
        path: server/build/Release/tfs.exe
