name: Forgotten Server 1.4 Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  VCPKG_ROOT: ${{ github.workspace }}/vcpkg

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Clone vcpkg
      run: git clone https://github.com/Microsoft/vcpkg.git
    
    - name: Bootstrap vcpkg
      run: |
        cd vcpkg
        .\bootstrap-vcpkg.bat
    
    - name: Setup vcpkg
      uses: lukka/run-vcpkg@v11
      with:
        vcpkgDirectory: '${{ github.workspace }}/vcpkg'
    
    - name: Add vcpkg.json
      run: |
        echo '{
            "name": "forgotten-server",
            "version": "1.4.0",
            "dependencies": [
                "boost",
                "openssl",
                "mysql-connector-cpp",
                "asio",
                "cryptopp",
                "pugixml",
                "fmt",
                "luajit",
                "lua",
                "threads"
            ]
        }' > ${{ github.workspace }}/vcpkg/vcpkg.json
    
    - name: Setup Python for Google Drive Download
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install gdown for Google Drive Download
      run: pip install gdown
    
    - name: Download Server.zip from Google Drive
      run: |
        gdown 1mbP66SZCS0jK7DKeQKb3PcvdgtmDdDNq
    
    - name: Extract Server.zip
      run: |
        Expand-Archive -Path Server.zip -DestinationPath ./server
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Install Dependencies via vcpkg
      run: |
        ${{ github.workspace }}/vcpkg/vcpkg install boost:x64-windows
        ${{ github.workspace }}/vcpkg/vcpkg install openssl:x64-windows
        ${{ github.workspace }}/vcpkg/vcpkg install mysql-connector-cpp:x64-windows
        ${{ github.workspace }}/vcpkg/vcpkg install asio:x64-windows
        ${{ github.workspace }}/vcpkg/vcpkg install cryptopp:x64-windows
        ${{ github.workspace }}/vcpkg/vcpkg install pugixml:x64-windows
        ${{ github.workspace }}/vcpkg/vcpkg install fmt:x64-windows
        ${{ github.workspace }}/vcpkg/vcpkg install luajit:x64-windows
        ${{ github.workspace }}/vcpkg/vcpkg install lua:x64-windows
        ${{ github.workspace }}/vcpkg/vcpkg install threads:x64-windows
    
    - name: Configure CMake
      run: |
        cd server
        cmake -B build \
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake \
        -DVCPKG_TARGET_TRIPLET=x64-windows \
        -DCMAKE_BUILD_TYPE=Release \
        -DUSE_LUAJIT=ON
    
    - name: Build Project
      run: |
        cd server
        cmake --build build --config Release
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: tfs-windows-build
        path: server/build/Release/tfs.exe
