name: Build ForgottenServer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install curl
      run: choco install curl -y

    - name: Download Server Files
      run: |
        curl -L "https://drive.google.com/uc?export=download&id=1mbP66SZCS0jK7DKeQKb3PcvdgtmDdDNq" -o Server.zip
        7z x Server.zip

    - name: Install vcpkg
      run: |
        git clone https://github.com/Microsoft/vcpkg.git
        .\vcpkg\bootstrap-vcpkg.bat
        .\vcpkg\vcpkg integrate install

    - name: Install dependencies
      run: |
        .\vcpkg\vcpkg install boost-asio:x64-windows
        .\vcpkg\vcpkg install boost-filesystem:x64-windows
        .\vcpkg\vcpkg install boost-iostreams:x64-windows
        .\vcpkg\vcpkg install boost-lockfree:x64-windows
        .\vcpkg\vcpkg install boost-system:x64-windows
        .\vcpkg\vcpkg install boost-variant:x64-windows
        .\vcpkg\vcpkg install cryptopp:x64-windows
        .\vcpkg\vcpkg install luajit:x64-windows
        .\vcpkg\vcpkg install mpir:x64-windows
        .\vcpkg\vcpkg install pugixml:x64-windows
        .\vcpkg\vcpkg install mysql-connector-cpp:x64-windows

    - name: Configure CMake
      run: |
        cd Server
        mkdir build
        cd build
        cmake -DCMAKE_TOOLCHAIN_FILE=../../vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x64-windows -G "Visual Studio 17 2022" -A x64 ..

    - name: Build
      run: |
        cd Server/build
        cmake --build . --config Release

    - name: Create artifacts
      run: |
        mkdir artifact
        copy Server\build\Release\theforgottenserver.exe artifact\
        copy Server\build\Release\*.dll artifact\

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: tfs-windows
        path: artifact\
