name: Auto build Aseprite

on:
  push:
    branches: ["main"]

permissions:
  contents: write

jobs:
  auto-build:
    name: Auto build Aseprite for Windows x64
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Ninja
        run: |
          choco install ninja -y

      - name: Install Python requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Download libjpeg-turbo (Manual)
        run: |
          Invoke-WebRequest -Uri "https://github.com/libjpeg-turbo/libjpeg-turbo/archive/refs/tags/2.1.91.zip" -OutFile "libjpeg-turbo-main.zip"
          7z x libjpeg-turbo-main.zip -o"skia/third_party/externals"
          Move-Item -Path "skia/third_party/externals/libjpeg-turbo-2.1.91" -Destination "skia/third_party/externals/libjpeg-turbo"
          Remove-Item libjpeg-turbo-main.zip

      - name: Download Skia (Manual)
        run: |
          Invoke-WebRequest -Uri "https://github.com/aseprite/skia/releases/download/m102-861e474/skia-m102-861e474.zip" -OutFile "skia-m102-861e474.zip"
          7z x skia-m102-861e474.zip -o"skia"
          Remove-Item skia-m102-861e474.zip

      - name: Setup MSVC Developer Command Prompt
        uses: TheMrMilchmann/setup-msvc-dev@v3
        with:
          arch: x64

      - name: Build Aseprite
        run: |
          mkdir build
          cd build
          cmake "../aseprite" -G Ninja -DCMAKE_BUILD_TYPE=MinSizeRel -DLAF_BACKEND=skia -DSKIA_DIR="../skia" -DSKIA_LIBRARY_DIR="../skia/out/Release-x64" -DSKIA_LIBRARY="../skia/out/Release-x64/skia.lib"
          ninja aseprite
          copy "C:/Windows/System32/libcrypto-1_1-x64.dll" ./bin

      - name: Get version
        id: get_version
        run: |
          $version = Get-Content version.txt
          echo "version=$version" >> $env:GITHUB_OUTPUT

      - name: Zip Aseprite
        run: |
          cd build/bin
          7z a ../../Aseprite-Windows-x64-${{ steps.get_version.outputs.version }}.zip *

      - name: GH Release
        uses: softprops/action-gh-release@v2.0.4
        with:
          name: Aseprite-Windows-x64-${{ steps.get_version.outputs.version }}
          tag_name: ${{ steps.get_version.outputs.version }}
          files: |
            Aseprite-Windows-x64-${{ steps.get_version.outputs.version }}.zip
